CREATE TABLE IF NOT EXISTS `web_stories` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `image_path` varchar(500) DEFAULT NULL,
  `link_url` varchar(500) DEFAULT NULL,
  `is_generated` tinyint(1) DEFAULT 0 COMMENT '0: uploaded, 1: AI generated',
  `generation_prompt` text DEFAULT NULL COMMENT 'OpenAI prompt used for image generation',
  `openai_image_id` varchar(255) DEFAULT NULL COMMENT 'OpenAI image generation ID',
  `is_active` tinyint(1) DEFAULT 1,
  `display_order` int(11) DEFAULT 1,
  `view_count` int(11) DEFAULT 0,
  `click_count` int(11) DEFAULT 0,
  `lang_id` int(11) unsigned DEFAULT 1,
  `category_id` int(11) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_display_order` (`display_order`),
  KEY `idx_lang_id` (`lang_id`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;