#!/usr/bin/env php
<?php

// Minimum PHP version
$minPhpVersion = '8.1';
if (version_compare(PHP_VERSION, $minPhpVersion, '<')) {
    fwrite(STDERR, sprintf("Your PHP version must be %s or higher.", $minPhpVersion) . PHP_EOL);
    exit(1);
}

// Path to the front controller directory
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);

require FCPATH . 'app/Config/Paths.php';
$paths = new Config\Paths();

require $paths->systemDirectory . '/Boot.php';

exit(CodeIgniter\Boot::bootSpark($paths));

