<?php

namespace App\Commands;

use App\Libraries\NewsletterAIService;
use App\Libraries\NewsletterSenderService;
use App\Models\NewsletterEditorialLineModel;
use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

/**
 * Planeja edições da newsletter para as linhas editoriais cujo horário de envio
 * coincide com o momento atual. Para cada linha:
 *   1. Verifica se já existe send do dia para o slot
 *   2. Gera edição via NewsletterAIService
 *   3. Cria send (status=approved se ai_auto_publish, senão draft)
 *
 * Rodar via cron: a cada 5 min é OK; idempotente.
 */
class NewsletterScheduler extends BaseCommand
{
    protected $group = 'Newsletter';
    protected $name = 'newsletter:scheduler';
    protected $description = 'Plan newsletter editions for lines whose send_times match the current slot.';

    public function run(array $params)
    {
        $force = in_array('--force', $params, true);
        $onlyLine = null;
        foreach ($params as $p) {
            if (strpos($p, '--line=') === 0) {
                $onlyLine = (int) substr($p, 7);
            }
        }

        $lineModel = new NewsletterEditorialLineModel();
        $aiService = new NewsletterAIService();
        $sender = new NewsletterSenderService();
        $db = \Config\Database::connect();

        $lines = $lineModel->getAll(true);
        $now = new \DateTime('now');
        $todayStr = $now->format('Y-m-d');
        $nowSlot = $now->format('H:i');

        $planned = 0;
        $skipped = 0;
        $errors = 0;

        foreach ($lines as $line) {
            if ($onlyLine !== null && (int) $line->id !== $onlyLine) {
                continue;
            }
            $times = json_decode($line->send_times ?? '[]', true);
            if (!is_array($times) || empty($times)) {
                $skipped++;
                continue;
            }

            $matchSlot = null;
            foreach ($times as $t) {
                $t = trim((string) $t);
                if (!preg_match('/^\d{1,2}:\d{2}$/', $t)) continue;
                if ($force || $this->slotMatches($nowSlot, $t)) {
                    $matchSlot = $t;
                    break;
                }
            }

            if ($matchSlot === null) {
                $skipped++;
                continue;
            }

            // honour the editorial line cadence (daily/weekly/monthly/on_demand)
            if (!$force && !$this->frequencyAllows($line, $db)) {
                CLI::write("Line {$line->slug}: frequency '" . ($line->frequency ?? 'daily') . "' not due yet, skipping.", 'yellow');
                $skipped++;
                continue;
            }

            // dedupe: did we already plan a send for this line+slot today?
            $existing = $db->table('newsletter_sends')
                ->where('editorial_line_id', $line->id)
                ->where('DATE(generated_at)', $todayStr)
                ->where('slot', $matchSlot)
                ->whereIn('status', ['draft', 'approved', 'sending', 'sent'])
                ->countAllResults();
            if ($existing > 0 && !$force) {
                CLI::write("Line {$line->slug}: send for slot {$matchSlot} today already exists, skipping.", 'yellow');
                $skipped++;
                continue;
            }

            $edition = $aiService->generateEdition($line);
            if (!empty($edition['error'])) {
                CLI::write("Line {$line->slug}: AI error -> " . $edition['error'], 'red');
                $errors++;
                continue;
            }

            $sendId = $sender->buildSendFromEdition((int) $line->id, $edition, ['slot' => $matchSlot]);
            $planned++;
            CLI::write("Line {$line->slug}: send $sendId created (status=" . (($line->ai_auto_publish ?? 0) ? 'approved' : 'draft') . ")", 'green');
        }

        CLI::write("Done. planned=$planned skipped=$skipped errors=$errors");
    }

    /**
     * Gate generation by the line cadence. send_times only carries times of day, so
     * without this a "weekly" line whose slot matches would fire every single day.
     *
     *   daily / unknown -> always allowed (per-slot dedupe prevents same-slot dupes)
     *   weekly          -> only if no edition was generated in the current ISO week
     *   monthly         -> only if no edition was generated in the current calendar month
     *   on_demand       -> never auto-generated by the scheduler
     */
    protected function frequencyAllows($line, $db): bool
    {
        $freq = strtolower(trim((string) ($line->frequency ?? 'daily')));
        if ($freq === 'on_demand') {
            return false;
        }
        if ($freq !== 'weekly' && $freq !== 'monthly') {
            return true;
        }

        $last = $db->table('newsletter_sends')
            ->where('editorial_line_id', $line->id)
            ->whereIn('status', ['draft', 'approved', 'sending', 'sent'])
            ->orderBy('generated_at', 'DESC')
            ->limit(1)
            ->get()->getRow();
        if (!$last || empty($last->generated_at)) {
            return true;
        }

        $lastDt = new \DateTime($last->generated_at);
        $now    = new \DateTime('now');
        if ($freq === 'weekly') {
            return $lastDt->format('o-W') !== $now->format('o-W'); // ISO year-week
        }
        return $lastDt->format('Y-m') !== $now->format('Y-m');     // calendar month
    }

    /**
     * Match a slot if "now HH:MM" is within +/- 4 min of the configured slot
     * (allows for a 5-min cron + small clock drift without duplicating).
     */
    protected function slotMatches(string $now, string $slot): bool
    {
        $toMin = function (string $hm): int {
            $parts = explode(':', $hm);
            return ((int) $parts[0]) * 60 + (int) $parts[1];
        };
        $delta = abs($toMin($now) - $toMin($slot));
        return $delta <= 4;
    }
}
